version: '3.9'
services:
  api:
    build:
      context: ./backend/Ecom.Api
      dockerfile: Dockerfile
    container_name: ecommerce-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql,1433;Database=EcommerceDb;User Id=sa;Password=Your_strong_Passw0rd!;TrustServerCertificate=True
    depends_on:
      - mssql
      - redis

  frontend:
    build:
      context: ./frontend/storefront
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
      - "4200:80"
    depends_on:
      - api

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ecommerce-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_strong_Passw0rd!
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  redis:
    image: redis:7-alpine
    container_name: ecommerce-redis
    ports:
      - "6379:6379"

  adminer:
    image: adminer:latest
    container_name: ecommerce-adminer
    ports:
      - "8080:8080"
    depends_on:
      - mssql

volumes:
  mssql_data:
